#! /bin/sh

MODULES="/etc/modules"

start() {
	while read module
	do
		modprobe $module
	done <$MODULES
	echo "OK"
}

case "$1" in
	start)
		start
		;;
	*)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
